#!/usr/bin/env python3
"""build_indexes.py — generate per-domain MOC (index) notes so the vault HIERARCHY
shows up in Obsidian's graph view (the graph only renders links, not folders).

For every domain folder (and sub-folder) it writes a folder-note `<folder>/<folder>.md`
that links DOWN to the docs + sub-domain indexes it contains, and UP to its parent
index (top-level domains point up to `_home`). Re-run it after adding/moving docs —
it's idempotent and fully owns these index files (don't hand-edit them).

  python3 build_indexes.py [VAULT]   # VAULT defaults to $KNOWLEDGE_VAULT, then ~/Knowledge

Skips: .obsidian/, reference/ (has its own hand-kept reference.md MOC), attachments/.
"""
import os, re, sys

SKIP = {".obsidian", "reference"}
GEN_MARK = "<!-- AUTO-GENERATED by build_indexes.py — 不要手改;改了会被覆盖 -->"


def title_of(md):
    head = open(md, encoding="utf-8").read(800)
    m = re.search(r"^title:\s*(.+)$", head, re.M)
    t = m.group(1).strip() if m else os.path.splitext(os.path.basename(md))[0]
    return t.replace("|", "/").replace("]", ")").replace("[", "(")


def is_index(path, folder):
    return os.path.basename(path) == os.path.basename(folder) + ".md"


def has_docs(d):
    """True if d (recursively) contains a real doc (an .md that isn't a folder-note)."""
    for root, dirs, files in os.walk(d):
        dirs[:] = [x for x in dirs if x not in SKIP and x != "attachments"]
        for f in files:
            if f.endswith(".md") and not is_index(os.path.join(root, f), root):
                return True
    return False


def build(d, parent_index, vault):
    base = os.path.basename(d)
    idx_path = os.path.join(d, base + ".md")
    docs = sorted(
        f for f in os.listdir(d)
        if f.endswith(".md") and os.path.isfile(os.path.join(d, f)) and f != base + ".md"
    )
    subs = sorted(
        x for x in os.listdir(d)
        if os.path.isdir(os.path.join(d, x)) and x not in SKIP and x != "attachments"
        and has_docs(os.path.join(d, x))
    )

    L = ["---", f"title: {base} — 索引", "type: moc", "tags:", "  - moc", "---", "",
         f"# {base}", "", f"> 上级：[[{parent_index}]]", "", GEN_MARK, ""]
    if subs:
        L += ["## 子域", ""]
        L += [f"- [[{s}]]" for s in subs]
        L += [""]
    if docs:
        L += ["## 文档", ""]
        for f in docs:
            fb = os.path.splitext(f)[0]
            L.append(f"- [[{fb}|{title_of(os.path.join(d, f))}]]")
        L += [""]
    open(idx_path, "w", encoding="utf-8").write("\n".join(L))
    print("  +", os.path.relpath(idx_path, vault))

    for s in subs:
        build(os.path.join(d, s), base, vault)


def main(vault):
    domains = sorted(
        os.path.join(vault, n) for n in os.listdir(vault)
        if os.path.isdir(os.path.join(vault, n)) and n not in SKIP and not n.startswith(".")
        and has_docs(os.path.join(vault, n))
    )
    print(f"build_indexes: {len(domains)} top-level domains under {vault}")
    for dom in domains:
        build(dom, "_home", vault)
    print("done. (_home.md is hand-maintained — not generated)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1
         else os.environ.get("KNOWLEDGE_VAULT") or os.path.expanduser("~/Knowledge"))
